version: '3'

services:
  atlas:
    build: .
    volumes:
      - atlas_centos:/tmp/atlas_src
      - atlas_repos:/root/.m2/repository
    # ports:
    #   - "21000:21000"
    container_name: apache_atlas
    restart: unless-stopped
    hostname: atlas
    environment:
     - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "http://127.0.0.1:21000"]
      start_period: 5s
      interval: 15s
      timeout: 1s
    cpus: 2
    mem_limit: 4G
    mem_reservation: 4G
    # networks:
    #   - default

# networks:
#   default:
#     external: true
#     name: $NETWORK_NAME

volumes:
  atlas_centos:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/docker_apache_atlas/atlas
  atlas_repos:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/docker_apache_atlas/repos
