version: "3"

services:
  atlas:
    image: sburn/apache-atlas:2.3.0
    ports:
      - 21000:21000
    container_name: atlas
    restart: unless-stopped
    hostname: atlas
    # networks:
    #   - default

# networks:
#   default:
#     external: true
#     name: skynet


volumes:
  atlas_centos:
    driver_opts:
      o: bind
      type: none
      device: /home/nick/Docker/docker_apache_atlas/atlas
  atlas_repos:
    driver_opts:
      o: bind
      type: none
      device: /home/nick/Docker/docker_apache_atlas/repos