version: "3"

services:
  atlas:
    image: sburn/apache-atlas:2.3.0
    ports:
      - 21000:21000
    container_name: apache_atlas
    restart: unless-stopped
    hostname: atlas
    healthcheck:
      test: curl --fail http://localhost:21000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    # networks:
    #   - default

# networks:
#   default:
#     external: true
#     name: skynet