version: "3"

services:
  atlas:
    image: sburn/apache-atlas:2.3.0
    ports:
      - 21000:21000
    container_name: atlas
    restart: unless-stopped
    hostname: atlas
    volumes:
      - atlas_conf:/apache-atlas/conf
      - atlas_data:/apache-atlas/data
      - atlas_logs:/apache-atlas/logs
    # networks:
    #   - default

# networks:
#   default:
#     external: true
#     name: $NETWORK

volumes:
  atlas_conf:
    driver_opts:
      o: bind
      type: none
      device: $CONF_VOLUME
  atlas_data:
    driver_opts:
      o: bind
      type: none
      device: $DATA_VOLUME
  atlas_logs:
    driver_opts:
      o: bind
      type: none
      device: $LOGS_VOLUME
